#ifndef UBTDOWNLOADLISTITEMWIDGET_GLOBAL_H
#define UBTDOWNLOADLISTITEMWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBTDOWNLOADLISTITEMWIDGET_LIBRARY)
#  define UBTDOWNLOADLISTITEMWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UBTDOWNLOADLISTITEMWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UBTDOWNLOADLISTITEMWIDGET_GLOBAL_H
