#ifndef UBTSERVERCOMMUNICATION_GLOBAL_H
#define UBTSERVERCOMMUNICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBTSERVERCOMMUNICATION_LIBRARY)
#  define UBTSERVERCOMMUNICATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UBTSERVERCOMMUNICATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UBTSERVERCOMMUNICATION_GLOBAL_H
